title: Alexandre Boulch
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


collections:
  publications:
    permalink: "/:collection/:path/"
    output: true
    name: publications
    nav_exclude: false
    search_exclude: false
    sort_by: date


callouts:
  warning:
    title: Warning
    color: red
  note:
    color: purple
